import { CONFIG } from './config.js';
import { createShowcase, applyAction } from './core.js';
const KEY='salamandra.demo.state.v1',USER='salamandra.demo.user.v1';
const GAS_SESSION='salamandra.apps-script.session.v1',appsScript=CONFIG.backend==='apps-script';
export const shared=Boolean(CONFIG.apiBase);
export const sessionRefreshMs=appsScript?300000:0;
let channel=!shared&&'BroadcastChannel'in window?new BroadcastChannel('salamandra-demo'):null;
let memory=null;
function read(){try {return JSON.parse(localStorage.getItem(KEY))||createShowcase();}catch{return memory||createShowcase();}}
function save(s){memory=s;try{localStorage.setItem(KEY,JSON.stringify(s));}catch{throw new Error('No se pudo guardar la demo. Habilita el almacenamiento del navegador.');}}
async function request(route,options={},timeout=10000){const abort=new AbortController(),timer=setTimeout(()=>abort.abort(),timeout);try{const response=await fetch(CONFIG.apiBase+route,{credentials:'include',cache:'no-store',...options,signal:abort.signal});const data=await response.json();if(!response.ok){const error=new Error(data.message||'No se pudo conectar.');error.status=response.status;throw error;}return data;}finally{clearTimeout(timer);}}
function gasPayload(route,payload={}){const sessionToken=sessionStorage.getItem(GAS_SESSION);return {route,...payload,...(sessionToken?{sessionToken}:{})};}
async function gas(route,payload={},timeout=60000){const abort=new AbortController(),timer=setTimeout(()=>abort.abort(),timeout);try{const response=await fetch(CONFIG.apiBase,{method:'POST',headers:{'Content-Type':'text/plain;charset=UTF-8'},body:JSON.stringify(gasPayload(route,payload)),cache:'no-store',redirect:'follow',signal:abort.signal});const envelope=await response.json();if(!response.ok||envelope.ok===false){const error=new Error(envelope.error||envelope.message||'Google Apps Script no pudo completar la solicitud.');error.status=envelope.status||response.status;throw error;}return envelope.data;}finally{clearTimeout(timer);}}
async function gasPublic(route,params={}){const url=new URL(CONFIG.apiBase);url.searchParams.set('route',route);url.searchParams.set('_',Date.now());for(const [key,value]of Object.entries(params))if(value!=null)url.searchParams.set(key,value);const response=await fetch(url,{cache:'no-store',redirect:'follow'}),envelope=await response.json();if(!response.ok||envelope.ok===false){const error=new Error(envelope.error||'Google Apps Script no pudo completar la consulta.');error.status=envelope.status||response.status;throw error;}return envelope.data;}
function cleanOAuthQuery(returnHash=''){const url=new URL(location.href);for(const key of ['code','state','error','error_description','scope'])url.searchParams.delete(key);const query=url.searchParams.toString();history.replaceState(null,'',url.pathname+(query?'?'+query:'')+(returnHash?'#'+returnHash:url.hash));}
function markOAuthFailed(){history.replaceState(null,'',location.pathname+'?auth=failed'+location.hash);}
export async function fetchSnapshot(){if(appsScript)return gasPublic('state');if(shared)return request('/state');const state=read();save(state);return {state,sourceSyncedAt:Date.now(),mode:'demo',shared:false};}
export async function session(){if(appsScript){const query=new URLSearchParams(location.search),code=query.get('code'),oauthState=query.get('state');if(query.has('error')){markOAuthFailed();throw new Error('No se autorizó el acceso con start.gg.');}if(code&&oauthState){try{const result=await gas('auth-complete',{code,state:oauthState});sessionStorage.setItem(GAS_SESSION,result.sessionToken);cleanOAuthQuery(result.returnHash);return result.user;}catch(error){markOAuthFailed();throw error;}}if(!sessionStorage.getItem(GAS_SESSION))return null;try{return (await gas('session')).user;}catch(error){if(error.status===401)sessionStorage.removeItem(GAS_SESSION);throw error;}}if(shared)return (await request('/session')).user;try{return JSON.parse(sessionStorage.getItem(USER))||null;}catch{return null;}}
export async function beginOAuth(){if(appsScript)return (await gasPublic('auth-start',{returnHash:location.hash.slice(1)})).url;return CONFIG.apiBase+'/auth/startgg';}
export async function login(accountId){if(shared)return (await request('/demo/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({accountId})})).user;const state=read(),p=state.players.find(x=>x.id===accountId);if(accountId!=='staff'&&!p)throw new Error('Cuenta no encontrada.');const user=accountId==='staff'?{id:'staff',name:'Equipo Salamandra',role:'admin',playerId:state.players[0].id}:{id:p.id,name:p.name,role:'player',playerId:p.id};sessionStorage.setItem(USER,JSON.stringify(user));return user;}
export async function logout(){if(appsScript){try{if(sessionStorage.getItem(GAS_SESSION))await gas('logout');}finally{sessionStorage.removeItem(GAS_SESSION);}return;}if(shared)await request('/logout',{method:'POST'});else sessionStorage.removeItem(USER);}
export async function adminEvents(){if(appsScript)return (await gas('admin-events')).events;if(!shared)throw new Error('El selector requiere el servidor de Salamandra.');return (await request('/admin/events')).events;}
export async function selectEvent(eventReference){if(appsScript)return gas('select-event',{eventReference,idempotencyKey:crypto.randomUUID()},60000);if(!shared)throw new Error('El selector requiere el servidor de Salamandra.');return request('/admin/selection',{method:'POST',headers:{'Content-Type':'application/json','Idempotency-Key':crypto.randomUUID()},body:JSON.stringify({eventReference})},60000);}
export async function mutate(action,version){if(appsScript)return gas('action',{action,version,idempotencyKey:crypto.randomUUID()},60000);if(shared)return request('/actions',{method:'POST',headers:{'Content-Type':'application/json','Idempotency-Key':crypto.randomUUID()},body:JSON.stringify({action,version})});
  if((await session())?.role!=='admin')throw new Error('Acceso de administrador requerido.');
  const work=()=>{const state=read();if(state.version!==version){const e=new Error('El torneo cambió. Actualiza e inténtalo de nuevo.');e.status=409;throw e;}const next=applyAction(state,action);next.version=version+1;save(next);channel?.postMessage('changed');return {state:next,sourceSyncedAt:Date.now(),mode:'demo',shared:false};};
  return navigator.locks? navigator.locks.request('salamandra-demo-state',work):work();
}
export function subscribe(onChange){if(appsScript)return ()=>{};if(shared){const events=new EventSource(CONFIG.apiBase+'/events',{withCredentials:true});events.addEventListener('changed',onChange);return ()=>events.close();}const storage=e=>{if(e.key===KEY)onChange();};window.addEventListener('storage',storage);if(channel)channel.onmessage=onChange;return ()=>{window.removeEventListener('storage',storage);channel?.close();};}
